#ifndef REPORTENUMS_H
#define REPORTENUMS_H

#include <QObject>

class ReportEnums : public QObject
{
    Q_OBJECT

public:
    enum REPORT_TYPE{DETAIL_REPORT=1,SUMMARY_REPORT=2};
    enum REPORT_DATE_SELECTION_TYPE{SINGLE_DATE_REPORT=0,DATE_RANGE_REPORT=1,MONTH_REPORT=2};
    enum REPORT_GENERATION_SOURCE{CLICK_ON_LEFT_SELECTION=0,CLICK_ON_REPORT};

    Q_ENUM(REPORT_TYPE)
    Q_ENUM(REPORT_DATE_SELECTION_TYPE)
    Q_ENUM(REPORT_GENERATION_SOURCE)
};

#endif // REPORTENUMS_H
